### ISSUE TITLE
location scanning API receiver doesn't plot on map

### ISSUE THREAD

**Issue by rmnbrgr** [CiscoDevNet/devnet-express-meraki-issues#14]
Hi team,

when following [this](https://developer.cisco.com/learningcenter/tracks/meraki-devnet-express/meraki-location-scanning/dne-meraki-location-scanning-python/launch-the-location-scanning-api-receiver/) guide (new Meraki DNE), the location scanning demo doesn't plot the blue dots representing clients on the map. 
I suppose it's a problem with the path in `meraki-code/meraki-location-scanning-python/static/sample.js` as in this file `blue_circle.png` is referenced and Google Chrome shows the following error:
![Screenshot 2022-05-09 at 15 00 25](https://user-images.githubusercontent.com/55540070/167415279-0233f917-57c7-43c6-8d34-793b51671af7.png)

**Comment by annegentle** [comment]
This issue has been resolved; closing.
